/**
 * WatchLog v4 build.
 *
 *   node esbuild.config.mjs              -> dev watch build (sourcemaps, no minify)
 *   node esbuild.config.mjs production   -> one-shot production build
 *
 * Outputs into build/:
 *   main.js       bundled from src/main.ts (obsidian + electron + codemirror external)
 *   styles.css    concatenation of styles/*.css in numeric order, each with a banner
 *   manifest.json copied from the repo root
 */
import esbuild from "esbuild";
import builtins from "builtin-modules";
import { readFile, readdir, writeFile, mkdir, copyFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));
const outDir = join(root, "build");
const stylesDir = join(root, "styles");
const production = process.argv[2] === "production";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Source is at https://github.com/ — see src/ in the plugin repo.
*/
`;

/** Numeric-prefix ordering: 10-base.css < 20-cards.css < 100-x.css. */
function byNumericPrefix(a, b) {
  const na = Number.parseInt(a, 10);
  const nb = Number.parseInt(b, 10);
  if (Number.isNaN(na) && Number.isNaN(nb)) return a.localeCompare(b);
  if (Number.isNaN(na)) return 1;
  if (Number.isNaN(nb)) return -1;
  if (na !== nb) return na - nb;
  return a.localeCompare(b);
}

async function buildStyles() {
  let files = [];
  try {
    files = (await readdir(stylesDir)).filter((f) => f.endsWith(".css"));
  } catch {
    files = [];
  }
  files.sort(byNumericPrefix);

  const parts = [
    "/* WatchLog v4 — generated by esbuild.config.mjs. Edit styles/*.css, never this file.",
    " * Theming policy: zero hardcoded colors. Obsidian CSS vars + --wl-* custom props only.",
    " */",
  ];
  for (const file of files) {
    const css = await readFile(join(stylesDir, file), "utf8");
    parts.push(`\n/* ===== ${file} ===== */\n${css.trimEnd()}\n`);
  }
  await writeFile(join(outDir, "styles.css"), parts.join("\n"), "utf8");
  return files;
}

async function copyManifest() {
  await copyFile(join(root, "manifest.json"), join(outDir, "manifest.json"));
}

async function buildAssets() {
  const files = await buildStyles();
  await copyManifest();
  return files;
}

await mkdir(outDir, { recursive: true });

/** Rebuilds styles.css + manifest.json alongside every JS build. */
const assetsPlugin = {
  name: "wrl-assets",
  setup(build) {
    build.onEnd(async (result) => {
      if (result.errors.length > 0) return;
      const files = await buildAssets();
      console.log(`[wrl] styles.css <- ${files.length} partial(s): ${files.join(", ") || "(none)"}`);
    });
  },
};

const context = await esbuild.context({
  entryPoints: [join(root, "src/main.ts")],
  bundle: true,
  format: "cjs",
  target: "es2022",
  platform: "browser",
  logLevel: "info",
  sourcemap: production ? false : "inline",
  minify: production,
  treeShaking: true,
  outfile: join(outDir, "main.js"),
  banner: { js: banner },
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  plugins: [assetsPlugin],
});

if (production) {
  await context.rebuild();
  await context.dispose();
} else {
  await context.watch();
  console.log("[wrl] watching for changes…");
}
